apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.env.DATABASE_URL | quote }}
  JWT_SECRET: {{ .Values.env.JWT_SECRET | quote }}
  SMTP_USERNAME: {{ .Values.env.SMTP_USERNAME | quote }}
  SMTP_PASSWORD: {{ .Values.env.SMTP_PASSWORD | quote }}
